"""create job table

Revision ID: 2208ff24f5a1
Revises:
Create Date: 2026-09-21 21:05:49.040915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2208ff24f5a1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("site", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=511), nullable=False
        ),
        sa.Column(
            "company", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "job_type", sqlmodel.sql.sqltypes.AutoString(length=127), nullable=True
        ),
        sa.Column(
            "interval", sqlmodel.sql.sqltypes.AutoString(length=127), nullable=True
        ),
        sa.Column("min_amount", sa.Integer(), nullable=True),
        sa.Column("max_amount", sa.Integer(), nullable=True),
        sa.Column(
            "job_url", sqlmodel.sql.sqltypes.AutoString(length=1023), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("valid", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job")
    # ### end Alembic commands ###
